config/routes.rb
Rails.application.routes.draw do
  root to: 'status#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/queue'

  resources :add_update_ingests, only: :create
  resources :delete_ingests, only: :create
  resources :status, only: :index, defaults: { format: 'json' }

  post '/ingest/duke', to: 'mock#create'
end

app/models/add_update_ingest.rb
class AddUpdateIngest < Ingest
  IngestAdmin.call(self)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delete_ingest.rb
class DeleteIngest < Ingest
  IngestAdmin.call(self)
end

app/models/ingest.rb
class Ingest < ApplicationRecord
  has_one_attached :infile # Original file received by POST
  has_one_attached :argot  # Argot file for submission to TRLN ingest server

  # status constants
  ACCEPTED  = 0  # default
  FAILED    = 1  # an exception occurred in processing or ingest to TRLN
  COMPLETED = 2  # no errors occurred in processing or ingest to TRLN

  scope :failed, -> { where(status: FAILED) }
  scope :completed, -> { where(status: COMPLETED) }
  scope :older_than_days, ->(num) { where('created_at < ?', Time.current - num.days) }

  Stats = Struct.new(:total, :completed, :failed, :last)

  MIN_WEED_DAYS = 7

  def self.stats
    Stats.new(count, completed.count, failed.count, last)
  end

  def self.weed(num_days = nil)
    num = [MIN_WEED_DAYS, num_days.to_i].max
    older_than_days(num).destroy_all
  end

  def to_s
    format('%s <infile: %s, records: %s, status: %s, created: %s>', type, infile_filename, records || '[null]',
           status_label, created_at.localtime.to_s(:db))
  end

  def completed!
    update! status: COMPLETED
  end

  def completed?
    status == COMPLETED
  end

  def failed!
    update! status: FAILED
  end

  def failed?
    status == FAILED
  end

  def status_label
    I18n.t("tdi.ingest.status.#{status}")
  end

  def infile_filename
    infile.filename.to_s
  rescue StandardError
    nil
  end

  IngestAdmin.call(self)
end

app/models/ingest_admin.rb
module IngestAdmin
  def self.call(model)
    model.rails_admin do
      list do
        field :id
        field :type do
          pretty_value { value.sub(/Ingest/, '') }
        end
        field :created_at do
          date_format :db
        end
        field :records
        field :status do
          pretty_value { I18n.t("tdi.ingest.status.#{value}") }
        end
      end

      show do
        field :id
        field :type do
          pretty_value { value.sub(/Ingest/, '') }
        end
        field :created_at do
          date_format :db
        end
        field :records
        field :status do
          pretty_value { I18n.t("tdi.ingest.status.#{value}") }
        end
        field :infile do
          pretty_value do
            if value.present?
              path = bindings[:view].main_app.rails_blob_path(value)
              bindings[:view].content_tag(:a, value.filename, href: path)
            end
          end
        end
        field :argot do
          pretty_value do
            if value.present?
              path = bindings[:view].main_app.rails_blob_path(value)
              bindings[:view].content_tag(:a, value.filename, href: path)
            end
          end
        end
        field :updated_at do
          date_format :db
        end
      end
    end
  end
end

app/models/status.rb
class Status
  include ActiveModel::Model

  Data = Struct.new(:queue, :ingests)

  QUEUE_INFO = %i[pending processed working failed]

  attr_reader :meta, :data

  def initialize
    @meta = TrlnDiscoveryIngest::META
    @data = Data.new(queue, ingests)
  end

  def queue
    {} # FIXME: for Sidekiq?
  end

  def ingests
    { all: Ingest.stats,
      add_update: AddUpdateIngest.stats,
      delete: DeleteIngest.stats }
  end
end

app/models/trln_discovery_ingest/error.rb
module TrlnDiscoveryIngest
  class Error < ::RuntimeError; end
end

app/controllers/add_update_ingests_controller.rb
class AddUpdateIngestsController < IngestsController
  self.infile_pattern = /\Aadd\w+\.xml(\.gz)?\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
end

app/controllers/delete_ingests_controller.rb
class DeleteIngestsController < IngestsController
  self.infile_pattern = /\Adelete\w+\.txt\z/
end

app/controllers/ingests_controller.rb
class IngestsController < ApplicationController
  class InfileError < ::StandardError; end

  class_attribute :infile_pattern

  rescue_from InfileError do |e|
    render json: { error: e }, status: :bad_request
  end

  def create
    set_infile
    set_ingest
    queue_job
    render json: @ingest, status: :created
  end

  private

  def queue_job
    IngestJob.perform_later(@ingest)
  end

  def set_infile
    @infile = params.require(:infile)
    validate_filename!
  end

  def set_ingest
    @ingest = model.new
    @ingest.infile.attach(@infile)
    @ingest.save!
  end

  def validate_filename!
    return if @infile.original_filename =~ infile_pattern

    raise InfileError,
          "infile file name '#{@infile.original_filename}' does not match " \
          "required pattern for #{model} ingests: #{infile_pattern}"
  end

  def model
    controller_name.classify.constantize
  end
end

app/controllers/mock_controller.rb
class MockController < ApplicationController
  def create
    render plain: '202 Accepted', status: :accepted
  end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
  include ActionController::MimeResponds
  include ActionView::Rendering

  def index
    @status = Status.new
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @status, status: :ok }
    end
  end
end

app/views/status/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TRLN Discovery Ingest: Status</title>
    <style type="text/css">
      table { border-collapse: collapse; }
      table, td, th { border: 1px solid grey; }
      th, td { padding: 2px 0.5em; }
      th { text-align: left; }
    </style>
  </head>
  <body>
    <h1>TRLN Discovery Ingest: Status</h1>
    <p>
      <%= link_to "Machine-readable (JSON) version", status_index_path %>
    </p>
    <h2>Ingests</h2>
    <p>
      Summaries of ingest records in the <%= link_to "TDI database", "/admin" %>.
    </p>
    <table class="ingests">
      <thead>
	<tr>
	  <th>Type</th>
	  <th>Total</th>
	  <th>Complete</th>
	  <th>Failed</th>
	  <th>Last Created (Records, Status)</th>
	</tr>
      </thead>
      <tbody>
	<% %i( all add_update delete ).each do |type| %>
	<% ingests = @status.data.ingests[type] %>
	<tr class="<%= type %>">
	  <td><%= type.to_s.camelize %></td>
	  <td><%= ingests.total %></td>
	  <td><%= ingests.completed %></td>
	  <td class="<%= ingests.failed == 0 ? 'success' : 'warning' %>">
	    <%= ingests.failed %>
	  </td>
	  <td>
	    <% if ingests.last %>
	    <%= ingests.last.created_at.localtime.to_s(:db) %>
	    (<%= ingests.last.records || "NULL" %>, <%= ingests.last.status_label %>)
	    <% else %>
	    N/A
	    <% end %>
	  </td>
	</tr>
	<% end %>
      </tbody>
    </table>

    <h2>Queue</h2>
    <p>
      FIXME
    </p>

    <h2>Meta</h2>
    <p>
      TDI application metadata.
    </p>
    <table class="meta">
      <thead>
	<tr>
	  <th>Component</th>
	  <th>Version</th>
	</tr>
      </thead>
      <tbody>
	<% %i( tdi marc_to_argot argot spofford_client ).each do |comp| %>
	<tr class="<%= comp %>">
	  <td><%= comp %></td>
	  <td><%= @status.meta[comp][:version] %></td>
	</tr>
	<% end %>
      <tbody>
    </table>
  </body>
</html>